## Word Embedding

In [2]:
import numpy as np
from tensorflow import keras

In [3]:
#General reviews for a restaurant examples
#input data - reviews

#reviews = ['good food', 'amazing taste', 'great ambience', 'good restuarant', 'amazing service', 
#           'very bad service', 'poor taste', 'needs improvement', 'can be better', 'so so']

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

#Target labels - sentiments
sentiments = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
#Preprocessing the data
#This code is just for explanation

input_text = "amazing restaurant"
vocab_size = 30
keras.preprocessing.text.one_hot(input_text,vocab_size)

[21, 12]

one_hot() does not create one-hot vectors yet. Instead, it:

Splits the text into words → "amazing", "restaurant" <br>
Hashes each word into an integer between 1 and 30 (vocabulary size)

Here, a number is given to each word of the review like 4-amazing, 2-restaurant

In [5]:
#For each word in all the reviews, lets give the unique number. So we will use one-hot function of preprocessing text library.
vocab_size = 30
encoded_reviews = [keras.preprocessing.text.one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[24, 25], [21, 12], [3, 9], [22, 26, 5], [2, 29, 17], [1, 25], [20, 29, 22], [16, 4], [16, 28], [5, 12]]


In [6]:
#Now, we will pad the data to make all the reviews of equal length
max_length = 4
padded_reviews = keras.preprocessing.sequence.pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[24 25  0  0]
 [21 12  0  0]
 [ 3  9  0  0]
 [22 26  5  0]
 [ 2 29 17  0]
 [ 1 25  0  0]
 [20 29 22  0]
 [16  4  0  0]
 [16 28  0  0]
 [ 5 12  0  0]]


### Embedding

This adds an Embedding layer to your neural network. The Embedding layer converts integer-encoded words into dense vector representations.

It is the first layer of a typical NLP model when using sequences of word indices.

##### Explanation
Vocabulary size of 1000 (input dimension), Embedding vector size of 32 (output dimension) <br>
embedding_layer = tf.keras.layers.Embedding(input_dim=1000, output_dim=32)

In [7]:
vocab_size = 30 #integer assigned to all words should be <= 30
embeded_vector_size = 5 #output size
max_length = 4 #all the words/vectors should be of same length i.e. 4 after padding

model = keras.models.Sequential()

model.add(keras.layers.Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(1, activation='sigmoid')) #softmax

D:\VANSH\RAGs\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [8]:
x = padded_reviews
y = sentiments

In [9]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [10]:
#Training the model
model.fit(x, y, epochs=50, verbose=1)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 795ms/step - accuracy: 0.6000 - loss: 0.6876
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6000 - loss: 0.6867
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.6000 - loss: 0.6858
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.6000 - loss: 0.6849
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6000 - loss: 0.6840
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7000 - loss: 0.6832
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.7000 - loss: 0.6823
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7000 - loss: 0.6814
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7000 - loss: 0.6804
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7000 - loss: 0.6795
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.7000 - loss: 0.6786
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7000 - loss: 0.677

In [11]:
#Evaluate the model
model.evaluate(x,y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 246ms/step - accuracy: 1.0000 - loss: 0.6351


[0.6350671648979187, 1.0]

In [12]:
weights = model.get_layer('embedding').get_weights()[0] #extracts the embedding matrix (the main weights) from Embedding layer named 'embedding'
len(weights)

30

In [13]:
weights[13]

array([ 0.03560073,  0.01377466,  0.04728999,  0.0145342 , -0.0102967 ],
      dtype=float32)

In [15]:
# Example: embedding vector for word "learning"

from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(reviews)

In [21]:
print("Vector for 'horrible':", weights[tokenizer.word_index['horrible']])

Vector for 'horrible': [ 0.02277816 -0.01969417 -0.00529686 -0.02173518  0.01375637]


In [20]:
tokenizer.word_index['horrible']

14

In [23]:
weights[14]

array([ 0.02277816, -0.01969417, -0.00529686, -0.02173518,  0.01375637],
      dtype=float32)

In [17]:
word = 'horrible'

if word in tokenizer.word_index:
    print("Vector for 'horrible':", weights[tokenizer.word_index[word]])
else:
    print("Word not found in tokenizer vocabulary")

Vector for 'horrible': [ 0.02277816 -0.01969417 -0.00529686 -0.02173518  0.01375637]
